"""add_origin_and_discovery_run_id_to_project_references

Revision ID: 7b9923bb594d
Revises: 3c8b4e0d3b21
Create Date: 2025-09-21 16:04:02.956269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b9923bb594d'
down_revision: Union[str, None] = '3c8b4e0d3b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum types first
    project_reference_origin_enum = postgresql.ENUM('unknown', 'manual_discovery', 'auto_discovery', 'manual_add', 'import', 'upload', name='projectreferenceorigin')
    project_reference_origin_enum.create(op.get_bind())

    op.create_table('project_discovery_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('run_type', sa.Enum('manual', 'auto', name='projectdiscoveryruntype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='projectdiscoveryrunstatus'), server_default='pending', nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('sources', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('max_results', sa.Integer(), nullable=True),
    sa.Column('relevance_threshold', sa.Float(), nullable=True),
    sa.Column('settings_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_discovery_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'promoted', 'dismissed', name='projectdiscoveryresultstatus'), server_default='pending', nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('authors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('published_year', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_id'], ['references.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['project_discovery_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'fingerprint', name='uq_project_discovery_result_fingerprint')
    )
    op.drop_index('ix_ai_artifacts_paper', table_name='ai_artifacts')
    op.drop_index('ix_ai_artifacts_project', table_name='ai_artifacts')
    op.alter_column('branches', 'paper_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('branches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('branches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('branches', 'author_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_branches_author_id', table_name='branches')
    op.drop_index('ix_branches_paper_id', table_name='branches')
    op.alter_column('collaboration_participants', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('comments', 'resolved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_comments_commit_id', table_name='comments')
    op.drop_index('ix_comments_paper_id', table_name='comments')
    op.drop_index('ix_comments_user_id', table_name='comments')
    op.alter_column('commits', 'branch_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('commits', 'author_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('commits', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('commits', 'changes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_index('ix_commits_author_id', table_name='commits')
    op.drop_index('ix_commits_branch_id', table_name='commits')
    op.drop_index('ix_commits_timestamp', table_name='commits')
    op.alter_column('conflict_resolutions', 'merge_request_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('conflict_resolutions', 'resolved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('document_chunks', 'embedding',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('ix_meetings_project', table_name='meetings')
    op.alter_column('merge_requests', 'source_branch_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('merge_requests', 'target_branch_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('merge_requests', 'paper_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('merge_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('merge_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('merge_requests', 'author_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_merge_requests_author_id', table_name='merge_requests')
    op.drop_index('ix_merge_requests_paper_id', table_name='merge_requests')
    op.drop_index('ix_notifications_project', table_name='notifications')
    op.drop_index('ix_notifications_user', table_name='notifications')
    op.drop_index('ix_paper_references_paper', table_name='paper_references')
    op.drop_index('ix_paper_references_reference', table_name='paper_references')
    op.alter_column('project_members', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'accepted'::character varying"))
    op.drop_index('ix_project_members_project', table_name='project_members')
    op.drop_index('ix_project_members_user', table_name='project_members')
    op.drop_constraint('uq_project_membership', 'project_members', type_='unique')
    op.add_column('project_references', sa.Column('origin', sa.Enum('unknown', 'manual_discovery', 'auto_discovery', 'manual_add', 'import', 'upload', name='projectreferenceorigin'), server_default='unknown', nullable=False))
    op.add_column('project_references', sa.Column('discovery_run_id', sa.UUID(), nullable=True))
    op.drop_index('ix_project_references_project', table_name='project_references')
    op.drop_index('ix_project_references_reference', table_name='project_references')
    op.create_foreign_key(None, 'project_references', 'project_discovery_runs', ['discovery_run_id'], ['id'], ondelete='SET NULL')
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('references', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('references', 'authors',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('references', 'key_findings',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('references', 'limitations',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.drop_index('uq_refs_owner_paper_doi', table_name='references', postgresql_where='(doi IS NOT NULL)')
    op.drop_index('uq_refs_owner_paper_title_year_nodoi', table_name='references', postgresql_where='(doi IS NULL)')
    op.alter_column('research_papers', 'keywords',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('research_papers', 'authors',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.drop_index('ix_research_papers_project_id', table_name='research_papers')
    op.drop_index('ix_section_locks_paper_section', table_name='section_locks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_section_locks_paper_section', 'section_locks', ['paper_id', 'section_key'], unique=False)
    op.create_index('ix_research_papers_project_id', 'research_papers', ['project_id'], unique=False)
    op.alter_column('research_papers', 'authors',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('research_papers', 'keywords',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.create_index('uq_refs_owner_paper_title_year_nodoi', 'references', ['owner_id', sa.text("COALESCE(paper_id, '00000000-0000-0000-0000-000000000000'::uuid)"), sa.text("lower(regexp_replace(title::text, '\\s+'::text, ' '::text, 'g'::text))"), sa.text('COALESCE(year, 0)')], unique=False, postgresql_where='(doi IS NULL)')
    op.create_index('uq_refs_owner_paper_doi', 'references', ['owner_id', sa.text("COALESCE(paper_id, '00000000-0000-0000-0000-000000000000'::uuid)"), sa.text('lower(doi::text)')], unique=False, postgresql_where='(doi IS NOT NULL)')
    op.alter_column('references', 'limitations',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('references', 'key_findings',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('references', 'authors',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('references', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_constraint(None, 'project_references', type_='foreignkey')
    op.create_index('ix_project_references_reference', 'project_references', ['reference_id'], unique=False)
    op.create_index('ix_project_references_project', 'project_references', ['project_id'], unique=False)
    op.drop_column('project_references', 'discovery_run_id')
    op.drop_column('project_references', 'origin')
    op.create_unique_constraint('uq_project_membership', 'project_members', ['project_id', 'user_id'])
    op.create_index('ix_project_members_user', 'project_members', ['user_id'], unique=False)
    op.create_index('ix_project_members_project', 'project_members', ['project_id'], unique=False)
    op.alter_column('project_members', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'accepted'::character varying"))
    op.create_index('ix_paper_references_reference', 'paper_references', ['reference_id'], unique=False)
    op.create_index('ix_paper_references_paper', 'paper_references', ['paper_id'], unique=False)
    op.create_index('ix_notifications_user', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_project', 'notifications', ['project_id'], unique=False)
    op.create_index('ix_merge_requests_paper_id', 'merge_requests', ['paper_id'], unique=False)
    op.create_index('ix_merge_requests_author_id', 'merge_requests', ['author_id'], unique=False)
    op.alter_column('merge_requests', 'author_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('merge_requests', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('merge_requests', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('merge_requests', 'paper_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('merge_requests', 'target_branch_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('merge_requests', 'source_branch_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_meetings_project', 'meetings', ['project_id'], unique=False)
    op.alter_column('document_chunks', 'embedding',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('conflict_resolutions', 'resolved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('conflict_resolutions', 'merge_request_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_commits_timestamp', 'commits', ['timestamp'], unique=False)
    op.create_index('ix_commits_branch_id', 'commits', ['branch_id'], unique=False)
    op.create_index('ix_commits_author_id', 'commits', ['author_id'], unique=False)
    op.alter_column('commits', 'changes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('commits', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('commits', 'author_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('commits', 'branch_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_comments_user_id', 'comments', ['user_id'], unique=False)
    op.create_index('ix_comments_paper_id', 'comments', ['paper_id'], unique=False)
    op.create_index('ix_comments_commit_id', 'comments', ['commit_id'], unique=False)
    op.alter_column('comments', 'resolved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('collaboration_participants', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_branches_paper_id', 'branches', ['paper_id'], unique=False)
    op.create_index('ix_branches_author_id', 'branches', ['author_id'], unique=False)
    op.alter_column('branches', 'author_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('branches', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('branches', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('branches', 'paper_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_ai_artifacts_project', 'ai_artifacts', ['project_id'], unique=False)
    op.create_index('ix_ai_artifacts_paper', 'ai_artifacts', ['paper_id'], unique=False)
    op.drop_table('project_discovery_results')
    op.drop_table('project_discovery_runs')

    # Drop the enum types
    project_reference_origin_enum = postgresql.ENUM(name='projectreferenceorigin')
    project_reference_origin_enum.drop(op.get_bind())
    # ### end Alembic commands ###
